### ISSUE TITLE
link to PDF file with list of NAPs

### ISSUE THREAD

**Issue by enricomiletto** [public-transport/european-transport-feeds#13]
In the Motivation and in the Additional Information sections there's a link to the PDF file with the official list of NAPs.
That link is broken now.
Here's the new address:
https://transport.ec.europa.eu/system/files/2022-11/its-national-access-points.pdf

Cheers,
Enrico

**Comment by juliuste** [comment]
Thanks for reporting this, and sorry for the late response 😅 #12 updated the URL, so I'll close this issue, please re-open if I missed anything 🙂
