### ISSUE TITLE
Finnland Feed

### ISSUE THREAD

**Issue by Ge-Rag** [public-transport/european-transport-feeds#14]
The Finnland feed at "http://185.134.88.185/gtfs.zip" is outdated. Last update was in November 2022.
I found a new link at "http://traffic.navici.com/tiedostot/gtfs.zip" at following page:

https://developer.matka.fi/pages/en/home.php

The download link unfortunately only works with http not https (using curl), but it seems that the data is current and being updated daily.

**Comment by juliuste** [comment]
Thanks for reporting! I updated the feed list 🙂

**Comment by juliuste** [comment]
(HTTPS worked for me - using curl - so I used that for now, but please let me know if there are still any issues)
